// <auto-generated>
// THIS (.cs) FILE IS GENERATED BY MPC(MessagePack-CSharp). DO NOT CHANGE IT.
// </auto-generated>

#pragma warning disable 618
#pragma warning disable 612
#pragma warning disable 414
#pragma warning disable 168

#pragma warning disable SA1129 // Do not use default value type constructor
#pragma warning disable SA1309 // Field names should not begin with underscore
#pragma warning disable SA1312 // Variable names should begin with lower-case letter
#pragma warning disable SA1403 // File may only contain a single namespace
#pragma warning disable SA1649 // File name should match first type name

namespace MessagePack.Formatters.PixivApi
{
    public sealed class UserDatabaseInfoFormatter : global::MessagePack.Formatters.IMessagePackFormatter<global::PixivApi.UserDatabaseInfo>
    {

        public void Serialize(ref global::MessagePack.MessagePackWriter writer, global::PixivApi.UserDatabaseInfo value, global::MessagePack.MessagePackSerializerOptions options)
        {
            if (value == null)
            {
                writer.WriteNil();
                return;
            }

            global::MessagePack.IFormatterResolver formatterResolver = options.Resolver;
            writer.WriteArrayHeader(6);
            global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<global::PixivApi.User>(formatterResolver).Serialize(ref writer, value.User, options);
            global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<global::PixivApi.UserDetailProfile>(formatterResolver).Serialize(ref writer, value.Profile, options);
            global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<global::PixivApi.UserDetailProfilePublicity>(formatterResolver).Serialize(ref writer, value.ProfilePublicity, options);
            global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<global::PixivApi.UserDetailWorkspace>(formatterResolver).Serialize(ref writer, value.Workspace, options);
            writer.Write(value.IsMuted);
            global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<global::PixivApi.UserExtraInfo>(formatterResolver).Serialize(ref writer, value.ExtraInfo, options);
        }

        public global::PixivApi.UserDatabaseInfo Deserialize(ref global::MessagePack.MessagePackReader reader, global::MessagePack.MessagePackSerializerOptions options)
        {
            if (reader.TryReadNil())
            {
                return null;
            }

            options.Security.DepthStep(ref reader);
            global::MessagePack.IFormatterResolver formatterResolver = options.Resolver;
            var length = reader.ReadArrayHeader();
            var ____result = new global::PixivApi.UserDatabaseInfo();

            for (int i = 0; i < length; i++)
            {
                switch (i)
                {
                    case 0:
                        ____result.User = global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<global::PixivApi.User>(formatterResolver).Deserialize(ref reader, options);
                        break;
                    case 1:
                        ____result.Profile = global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<global::PixivApi.UserDetailProfile>(formatterResolver).Deserialize(ref reader, options);
                        break;
                    case 2:
                        ____result.ProfilePublicity = global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<global::PixivApi.UserDetailProfilePublicity>(formatterResolver).Deserialize(ref reader, options);
                        break;
                    case 3:
                        ____result.Workspace = global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<global::PixivApi.UserDetailWorkspace>(formatterResolver).Deserialize(ref reader, options);
                        break;
                    case 4:
                        ____result.IsMuted = reader.ReadBoolean();
                        break;
                    case 5:
                        ____result.ExtraInfo = global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<global::PixivApi.UserExtraInfo>(formatterResolver).Deserialize(ref reader, options);
                        break;
                    default:
                        reader.Skip();
                        break;
                }
            }

            reader.Depth--;
            return ____result;
        }
    }

}

#pragma warning restore 168
#pragma warning restore 414
#pragma warning restore 618
#pragma warning restore 612

#pragma warning restore SA1129 // Do not use default value type constructor
#pragma warning restore SA1309 // Field names should not begin with underscore
#pragma warning restore SA1312 // Variable names should begin with lower-case letter
#pragma warning restore SA1403 // File may only contain a single namespace
#pragma warning restore SA1649 // File name should match first type name
