// <auto-generated>
// THIS (.cs) FILE IS GENERATED BY MPC(MessagePack-CSharp). DO NOT CHANGE IT.
// </auto-generated>

#pragma warning disable 618
#pragma warning disable 612
#pragma warning disable 414
#pragma warning disable 168

#pragma warning disable SA1312 // Variable names should begin with lower-case letter
#pragma warning disable SA1649 // File name should match first type name

namespace MessagePack.Resolvers
{
    public class GeneratedResolver : global::MessagePack.IFormatterResolver
    {
        public static readonly global::MessagePack.IFormatterResolver Instance = new GeneratedResolver();

        private GeneratedResolver()
        {
        }

        public global::MessagePack.Formatters.IMessagePackFormatter<T> GetFormatter<T>()
        {
            return FormatterCache<T>.Formatter;
        }

        private static class FormatterCache<T>
        {
            internal static readonly global::MessagePack.Formatters.IMessagePackFormatter<T> Formatter;

            static FormatterCache()
            {
                var f = GeneratedResolverGetFormatterHelper.GetFormatter(typeof(T));
                if (f != null)
                {
                    Formatter = (global::MessagePack.Formatters.IMessagePackFormatter<T>)f;
                }
            }
        }
    }

    internal static class GeneratedResolverGetFormatterHelper
    {
        private static readonly global::System.Collections.Generic.Dictionary<global::System.Type, int> lookup;

        static GeneratedResolverGetFormatterHelper()
        {
            lookup = new global::System.Collections.Generic.Dictionary<global::System.Type, int>(18)
            {
                { typeof(global::PixivApi.ArtworkDatabaseInfo[]), 0 },
                { typeof(global::PixivApi.MetaPage[]), 1 },
                { typeof(global::PixivApi.Tag[]), 2 },
                { typeof(global::System.Collections.Generic.Dictionary<uint, global::PixivApi.FilePageExtraInfo>), 3 },
                { typeof(global::PixivApi.ArtworkType), 4 },
                { typeof(global::PixivApi.HideReason), 5 },
                { typeof(global::PixivApi.ArtworkDatabaseInfo), 6 },
                { typeof(global::PixivApi.FileExtraInfo), 7 },
                { typeof(global::PixivApi.ImageUrls), 8 },
                { typeof(global::PixivApi.Tag), 9 },
                { typeof(global::PixivApi.User), 10 },
                { typeof(global::PixivApi.UserDatabaseInfo), 11 },
                { typeof(global::PixivApi.UserDetailInfo), 12 },
                { typeof(global::PixivApi.UserDetailProfile), 13 },
                { typeof(global::PixivApi.UserDetailProfilePublicity), 14 },
                { typeof(global::PixivApi.UserDetailWorkspace), 15 },
                { typeof(global::PixivApi.UserExtraInfo), 16 },
                { typeof(global::PixivApi.UserPreview), 17 },
            };
        }

        internal static object GetFormatter(global::System.Type t)
        {
            int key;
            if (!lookup.TryGetValue(t, out key))
            {
                return null;
            }

            switch (key)
            {
                case 0: return new global::MessagePack.Formatters.ArrayFormatter<global::PixivApi.ArtworkDatabaseInfo>();
                case 1: return new global::MessagePack.Formatters.ArrayFormatter<global::PixivApi.MetaPage>();
                case 2: return new global::MessagePack.Formatters.ArrayFormatter<global::PixivApi.Tag>();
                case 3: return new global::MessagePack.Formatters.DictionaryFormatter<uint, global::PixivApi.FilePageExtraInfo>();
                case 4: return new MessagePack.Formatters.PixivApi.ArtworkTypeFormatter();
                case 5: return new MessagePack.Formatters.PixivApi.HideReasonFormatter();
                case 6: return new MessagePack.Formatters.PixivApi.ArtworkDatabaseInfoFormatter();
                case 7: return new MessagePack.Formatters.PixivApi.FileExtraInfoFormatter();
                case 8: return new MessagePack.Formatters.PixivApi.ImageUrlsFormatter();
                case 9: return new MessagePack.Formatters.PixivApi.TagFormatter();
                case 10: return new MessagePack.Formatters.PixivApi.UserFormatter();
                case 11: return new MessagePack.Formatters.PixivApi.UserDatabaseInfoFormatter();
                case 12: return new MessagePack.Formatters.PixivApi.UserDetailInfoFormatter();
                case 13: return new MessagePack.Formatters.PixivApi.UserDetailProfileFormatter();
                case 14: return new MessagePack.Formatters.PixivApi.UserDetailProfilePublicityFormatter();
                case 15: return new MessagePack.Formatters.PixivApi.UserDetailWorkspaceFormatter();
                case 16: return new MessagePack.Formatters.PixivApi.UserExtraInfoFormatter();
                case 17: return new MessagePack.Formatters.PixivApi.UserPreviewFormatter();
                default: return null;
            }
        }
    }
}

#pragma warning restore 168
#pragma warning restore 414
#pragma warning restore 618
#pragma warning restore 612

#pragma warning restore SA1312 // Variable names should begin with lower-case letter
#pragma warning restore SA1649 // File name should match first type name
